---
- hosts: nginx
  become: yes

  vars_files:
    - vars/nginx_vars.yml

  tasks:
    - name: Remove default Nginx configuration
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent
      tags:
        - config

    - name: Add custom Nginx configuration to container
      command: docker cp files/static-site.conf nginx-container:/etc/nginx/conf.d/static-site.conf
      tags:
        - config

    - name: Add Hello World HTML file to container
      command: docker cp files/index.html nginx-container:/usr/share/nginx/html/index.html
      tags:
        - hello-world

  handlers:
    - name: Reload Nginx
      command: nginx -s reload