---
- hosts: nginx
  become: yes

  vars_files:
    - vars/nginx_vars.yml

  tasks:
    - name: Update apt cache and install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
      tags:
        - install

    - name: Remove default Nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      tags:
        - config

    - name: Add custom Nginx configuration
      copy:
        src: files/static-site-config
        dest: "{{ nginx_config_dest }}"
        owner: root
        group: root
        mode: '0644'
      notify: Reload Nginx
      tags:
        - config

    - name: Enable custom Nginx configuration
      file:
        src: "{{ nginx_config_dest }}"
        dest: "{{ nginx_config_link }}"
        state: link
      notify: Reload Nginx
      tags:
        - config

    - name: Create Hello World HTML file
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
      tags:
        - hello-world

    - name: restart Nginx
      service:
        name: nginx
        state: restarted
      tags:
        - restart

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded