---
- hosts: postgresql
  become: yes
  
  vars_files:
    - vars/postgres_vars.yml

  tasks:
    - name: Add PostgreSQL APT repository
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main"
        state: present
        filename: "pgdg.list"
      tags:
        - install

    - name: Update apt cache
      apt:
        update_cache: yes
      tags:
        - install

    - name: Install PostgreSQL
      apt:
        name: "postgresql-{{ postgresql_version }}"
        state: present
      tags:
        - install

    - name: Ensure PostgreSQL service is running
      service:
        name: postgresql
        state: started
        enabled: yes
      tags:
        - service

    - name: Create PostgreSQL database
      become_user: postgres
      postgresql_db:
        name: "{{ postgresql_db }}"
        state: present
      tags:
        - db_config

    - name: Create PostgreSQL user
      become_user: postgres
      postgresql_user:
        name: "{{ postgresql_user }}"
        password: "{{ postgresql_password }}"
        state: present
      tags:
        - db_config

    - name: Grant privileges to user on database
      become_user: postgres
      postgresql_privs:
        db: "{{ postgresql_db }}"
        roles: "{{ postgresql_user }}"
        type: database
        privs: "ALL"
        state: present
      tags:
        - db_config

  handlers:
    - name: Restart PostgreSQL
      service:
        name: postgresql
        state: restarted