---
- hosts: tomcat
  become: yes
  
  vars_files:
    - vars/tomcat_vars.yml

  tasks:
    - name: Update the System Packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Create a Tomcat Group
      group: name=tomcat

    - name: Create a Tomcat User
      user: name=tomcat group=tomcat home=/usr/local/tomcat createhome=no 

    - name: Ajustar permissões do Tomcat
      file:
        path: "{{ tomcat_install_dir }}"
        state: directory
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        recurse: yes
      tags:
        - config

    - name: Change ownership of tomcat
      file: path={{ tomcat_install_dir }} owner={{ tomcat_user }} group={{ tomcat_group }} state=directory recurse=yes

    - name: configure tomcat user
      copy:
        src: files/tomcat-users.xml
        dest: "{{ tomcat_install_dir }}/conf/tomcat-users.xml"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
      notify:
        - Restart Tomcat

    - name: start tomcat in container
      command: /usr/share/tomcat/bin/startup.sh
      args:
        chdir: "/usr/share/tomcat/bin"

  handlers:
    - name: Restart Tomcat
      service:
        name: "{{ tomcat_service_name }}"
        state: restarted